import numpy as np
import pandas as pd
from helpers.Variable_class import Variable

# This module defines the master dictionary of model variable specifications.
# Each entry maps a variable key to a configured ``Variable`` instance.
#
# Notes on ``is_t_minus_one``:
# - ``False`` means no lag linkage is used.
# - A string value means this variable aquires the value of the variable indicated by the string in the previous time step. 
# 	This is used to automatically populate the first year of the time-series DataFrame with the calibration value of the indicated variable, 
# 	and to set up the correct lag relationships for dynamic updating in the model solution process.

sectors         = pd.read_csv("Solver/preprocessed_data/indexes/sectors.csv")["sector"].tolist()
energy_types    = pd.read_csv("Solver/preprocessed_data/indexes/energy_uses.csv")["energy_use"].tolist()
energy_consumers = pd.read_csv("Solver/preprocessed_data/indexes/energy_consumers.csv")["energy_consumer"].tolist()

sectors_nE         = [x for x in sectors if x != "ENERGY"]
sectors_plus_hh    = energy_consumers
energy_types_wo_PE = [x for x in energy_types if x != "PE"]

endo_aYij_indexes = [("ENERGY",x) for x in sectors]
endo_aYij_indexes.extend([(x,"ENERGY") for x in sectors_nE])


VARIABLES_SPECS = {
    'K':Variable(name= "K",
                dimension='scalar', 
                idx_labels=[], 
                is_t_minus_one=False, 
                bounds=(0, np.inf), 
                status="exo"),

    'wI':Variable(name= "wI", 
                  dimension='scalar', 
                  idx_labels=[], 
                  is_t_minus_one=False, 
                  bounds=(0, 1), 
                  status="exo"),

    'wB':Variable(name= "wB", 
                  dimension='scalar', 
                  idx_labels=[], 
                  is_t_minus_one=False, 
                  bounds=(-1, 1), 
                  status="exo"),

    'L':Variable(name= "L", 
                 dimension='scalar', 
                 idx_labels=[], 
                 is_t_minus_one=False, 
                 bounds=(0, np.inf), 
                 status="exo"),

    'pL': Variable(name= "pL",
                 dimension='scalar',
                 idx_labels=[],
                 is_t_minus_one=False,
                 bounds=(0,np.inf),
                 status="endo"),

    'pK':Variable(name= "pK",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'pI':Variable(name= "pI",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'B':Variable(name= "B",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),

    'R':Variable(name= "R",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'Ri':Variable(name= "Ri",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'Rg':Variable(name= "Rg",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'bKL':Variable(name= "bKL",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),

    'GDPPI':Variable(name= "GDPPI",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),

    'GDP':Variable(name= "GDP",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),
                  
    'Kj':Variable(name="Kj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'Lj':Variable(name="Lj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'KLj':Variable(name="KLj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pKLj':Variable(name="pKLj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Yj':Variable(name="Yj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pYj':Variable(name="pYj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Cj': Variable(name="Cj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pCj': Variable(name="pCj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Mj': Variable(name="Mj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names=["ENERGY"]),

    'pMj': Variable(name="pMj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'lambda_pXj': Variable(name="lambda_pXj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),
                  
    'Xj': Variable(name="Xj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names=["ENERGY"]),

    'Dj': Variable(name="Dj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pDj': Variable(name="pDj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Sj': Variable(name="Sj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pSj': Variable(name="pSj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Gj': Variable(name="Gj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Ij': Variable(name="Ij",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Yij': Variable(name="Yij",
				  dimension='matrix',
				  idx_labels=[sectors,
				  sectors],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'I':Variable(name="I",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'aYij':Variable(name="aYij",
				  dimension='matrix',
				  idx_labels=[sectors,
				  sectors],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  endo_names=endo_aYij_indexes),

    'pY_Ej':Variable(name="pY_Ej",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'E_vol':Variable(name="E_vol",
				  dimension='matrix',
				  idx_labels=[sectors_plus_hh, energy_types],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names = [("HOUSEHOLDS", "PAS"), ("HOUSEHOLDS", "R&C")]),

    'pE':Variable(name="pE",
				  dimension='matrix',
				  idx_labels=[sectors_plus_hh, energy_types],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'rhoE':Variable(name="rhoE",
				  dimension='matrix',
				  idx_labels=[sectors_plus_hh, energy_types_wo_PE],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),
                  
	'rhoM':Variable(name="rhoM",
				dimension='scalar',
				idx_labels=[],
				is_t_minus_one=False,
				bounds=(0, np.inf),
				status="exo"),
                
	'rhoX':Variable(name="rhoX",
				dimension='scalar',
				idx_labels=[],
				is_t_minus_one=False,
				bounds=(0, np.inf),
				status="exo"),
                
    'a_Ej':Variable(name="a_Ej",
				  dimension='matrix',
				  idx_labels=[sectors_plus_hh, energy_types],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'wG':Variable(name="wG",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, 1),
				  status="exo"),

    'GDPreal':Variable(name="GDPreal",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'tauSj':Variable(name="tauSj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-1,
				  1),
				  status="exo"),

    'tauYj':Variable(name="tauYj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-1,
				  1),
				  status="exo"),

    'bKLj':Variable(name="bKLj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'pCtp':Variable(name="pCtp",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="pCj",
				  bounds=(0, np.inf),
				  status="exo"),

    'Ctp':Variable(name="Ctp",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="Cj",
				  bounds=(0, np.inf),
				  status="exo"),

    'Gtp':Variable(name="Gtp",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="Gj",
				  bounds=(0, np.inf),
				  status="exo"),

    'Itp':Variable(name="Itp",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="Ij",
				  bounds=(0, np.inf),
				  status="exo"),

    'pXtp':Variable(name="pXtp",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="pXj",
				  bounds=(0, np.inf),
				  status="exo"),

    'Xtp':Variable(name="Xtp",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="Xj",
				  bounds=(0, np.inf),
				  status="exo"),

    'Mtp':Variable(name="Mtp",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="Mj",
				  bounds=(0, np.inf),
				  status="exo"),
                  
    'alphaKj':Variable(name="alphaKj",
				  dimension='vector',
				  idx_labels=sectors ,
				  is_t_minus_one=False ,
				  bounds=(0,1),
				  status = "exo"),

    'alphaLj':Variable(name="alphaLj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, 1),
				  status="exo"),
	
	'alphaLj_CobbDouglas':Variable(name="alphaLj_CobbDouglas",
				dimension='vector',
				idx_labels=sectors,
				is_t_minus_one=False,
				bounds=(0, 1),
				status="exo"),
	'alphaKj_CobbDouglas':Variable(name="alphaKj_CobbDouglas",
				dimension='vector',
				idx_labels=sectors,
				is_t_minus_one=False,
				bounds=(0, 1),
				status="exo"),
    'aKLj':Variable(name="aKLj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  endo_names=["ENERGY"]),

    'alphaCj_nE':Variable(name="alphaCj_nE",
				  dimension='vector',
				  idx_labels=sectors_nE,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'alphaGj':Variable(name="alphaGj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'alphaIj':Variable(name="alphaIj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'alphaXj':Variable(name="alphaXj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'alphaDj':Variable(name="alphaDj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'betaDj':Variable(name="betaDj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'betaMj':Variable(name="betaMj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'thetaj':Variable(name="thetaj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'csij':Variable(name="csij",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'sigmaXj':Variable(name="sigmaXj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'sigmaSj':Variable(name="sigmaSj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'sigmaKLj':Variable(name="sigmaKLj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'delta':Variable(name="delta",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, 1),
				  status="exo"),

    'aKLj0':Variable(name="aKLj0",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'aYij0':Variable(name="aYij0",
				  dimension='matrix',
				  idx_labels=[sectors,
				  sectors],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'pXj':Variable(name="pXj",
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names=["SERVICES"]),

    'lambda_KLM':Variable("lambda_KLM",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    "R_E":Variable("R_E",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),
                  
    "R_nE":Variable("R_nE",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'betaCj_nE':Variable(name="betaCj_nE",
				  dimension='vector',
				  idx_labels=sectors_nE,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'u_C':Variable(name="u_C",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    "gammaCj_nE":Variable(name="gammaCj_nE",
				  dimension='vector',
				  idx_labels=sectors_nE,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    "A_Cj_nE":Variable(name="A_Cj_nE",
				  dimension='vector',
				  idx_labels=sectors_nE,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    "normalisation_factor":Variable(name="normalisation_factor",
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    }
# Maps each VARIABLES_SPECS key to the corresponding attribute name on calibrationVariables.
# Populated here so that run.py can call var.initialize_calibration_value(cal, CALIBRATION_MAPPING)
# for every variable after instantiating calibrationVariables once.
CALIBRATION_MAPPING = {
    'K':                   'K0',
    'wI':                  'wI',
    'wB':                  'wB',
    'L':                   'L0',
    'pL':                  'pL0',
    'pK':                  'pK0',
    'pI':                  'pI0',
    'B':                   'B0',
    'R':                   'R0',
    'Ri':                  'Ri0',
    'Rg':                  'Rg0',
    'bKL':                 'bKL',
    'GDPPI':               'GDPPI',
    'GDP':                 'GDPreal',
    'Kj':                  'Kj0',
    'Lj':                  'Lj0',
    'KLj':                 'KLj0',
    'pKLj':                'pKLj0',
    'Yj':                  'Yj0',
    'pYj':                 'pYj0',
    'Cj':                  'Cj0',
    'pCj':                 'pCj0',
    'Mj':                  'Mj0',
    'pMj':                 'pMj0',
    "lambda_pXj":          'lambda_pXj',
    'pXj':                 'pXj0',
    'Xj':                  'Xj0',
    'Dj':                  'Dj0',
    'pDj':                 'pDj0',
    'Sj':                  'Sj0',
    'pSj':                 'pSj0',
    'Gj':                  'Gj0',
    'Ij':                  'Ij0',
    'Yij':                 'Yij0',
    'I':                   'I0',
    'aYij':                'aYij0',
    'pY_Ej':               'pY_Ej',
    'E_vol':               'E_vol',
    'pE':                  'pE',
    'rhoE':                'rhoE',
	'rhoM':                'rhoM',
	'rhoX':                'rhoX',
    'a_Ej':                'a_Ej',
    'wG':                  'wG',
    'GDPreal':             'GDPreal',
    'tauSj':               'tauSj0',
    'tauYj':               'tauYj0',
    'bKLj':                'bKLj',
    'pCtp':                'pCjtp',
    'Ctp':                 'Ctp',
    'Gtp':                 'Gtp',
    'Itp':                 'Itp',
    'pXtp':                'pXtp',
    'Xtp':                 'Xtp',
    'Mtp':                 'Mtp',
    'alphaKj':             'alphaKj',
    'alphaLj':             'alphaLj',
	'alphaLj_CobbDouglas': 'alphaLj_CobbDouglas',
	'alphaKj_CobbDouglas': 'alphaKj_CobbDouglas',
    'aKLj':                'aKLj',
    'alphaCj_nE':          'alphaCj0_nE',
    'alphaGj':             'alphaGj',
    'alphaIj':             'alphaIj',
    'alphaXj':             'alphaXj0',
    'alphaDj':             'alphaDj0',
    'betaDj':              'betaDj0',
    'betaMj':              'betaMj0',
    'thetaj':              'thetaj',
    'csij':                'csij',
    'sigmaXj':             'sigmaXj',
    'sigmaSj':             'sigmaSj',
    'sigmaKLj':            'sigmaKLj',
    'delta':               'delta',
    'aKLj0':               'aKLj0',
    'aYij0':               'aYij0',
    'pXj':                 'pXj0',
    'lambda_KLM':          'lambda_KLM',
    'R_E':                 'R_E',
    'R_nE':                'R_nE',
    'betaCj_nE':           'betaCj_nE',
    'u_C':                 'u_C',
    'gammaCj_nE':          'gammaCj_nE',
    'A_Cj_nE':             'A_Cj_nE',
    'normalisation_factor':'normalisation_factor',
}
