import numpy as np 
from simple_calibration import calibrationVariables
from import_GTAP_data import sectors
from Variable_class import Variable


endo_aYij_indexes = [("ENERGY",x) for x in sectors]
sectors_nE = [x for x in sectors if x != "ENERGY"]
endo_aYij_indexes.extend([(x,"ENERGY") for x in sectors_nE])
cal = calibrationVariables()

VARIABLES_SPECS = {
    'K':Variable(name= "K",
                calibration_value=cal.K0, 
                dimension='scalar', 
                idx_labels=[], 
                is_t_minus_one=False, 
                bounds=(0, np.inf), 
                status="exo"),

    'wI':Variable(name= "wI", 
                  calibration_value=cal.wI, 
                  dimension='scalar', 
                  idx_labels=[], 
                  is_t_minus_one=False, 
                  bounds=(0, 1), 
                  status="exo"),

    'wB':Variable(name= "wB", 
                  calibration_value=cal.wB, 
                  dimension='scalar', 
                  idx_labels=[], 
                  is_t_minus_one=False, 
                  bounds=(-1, 1), 
                  status="exo"),

    'L':Variable(name= "L", 
                 calibration_value=cal.L0, 
                 dimension='scalar', 
                 idx_labels=[], 
                 is_t_minus_one=False, 
                 bounds=(0, np.inf), 
                 status="exo"),

    'pL': Variable(name= "pL",
                 calibration_value=cal.pL0,
                 dimension='scalar',
                 idx_labels=[],
                 is_t_minus_one=False,
                 bounds=(0,np.inf),
                 status="endo"),

    'pK':Variable(name= "pK",
				  calibration_value=cal.pK0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'pI':Variable(name= "pI",
				  calibration_value=cal.pI0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'B':Variable(name= "B",
				  calibration_value=cal.B0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),

    'R':Variable(name= "R",
				  calibration_value=cal.R0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'Ri':Variable(name= "Ri",
				  calibration_value=cal.Ri0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'Rg':Variable(name= "Rg",
				  calibration_value=cal.Rg0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'bKL':Variable(name= "bKL",
				  calibration_value=cal.bKL,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),

    'GDPPI':Variable(name= "GDPPI",
				  calibration_value=cal.GDPPI,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),

    'GDP':Variable(name= "GDP",
				  calibration_value=cal.GDPreal,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),
                  
    'Kj':Variable(name="Kj",
				  calibration_value=cal.Kj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'Lj':Variable(name="Lj",
				  calibration_value=cal.Lj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'KLj':Variable(name="KLj",
				  calibration_value=cal.KLj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pKLj':Variable(name="pKLj",
				  calibration_value=cal.pKLj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Yj':Variable(name="Yj",
				  calibration_value=cal.Yj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pYj':Variable(name="pYj",
				  calibration_value=cal.pYj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Cj': Variable(name="Cj",
				  calibration_value=cal.Cj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pCj': Variable(name="pCj",
				  calibration_value=cal.pCj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Mj': Variable(name="Mj",
				  calibration_value=cal.Mj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names=["ENERGY"]),

    'pMj': Variable(name="pMj",
				  calibration_value=cal.pMj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names=["ENERGY"]),

    'Xj': Variable(name="Xj",
				  calibration_value=cal.Xj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names=["ENERGY"]),

    'Dj': Variable(name="Dj",
				  calibration_value=cal.Dj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pDj': Variable(name="pDj",
				  calibration_value=cal.pDj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Sj': Variable(name="Sj",
				  calibration_value=cal.Sj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pSj': Variable(name="pSj",
				  calibration_value=cal.pSj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Gj': Variable(name="Gj",
				  calibration_value=cal.Gj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Ij': Variable(name="Ij",
				  calibration_value=cal.Ij0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Yij': Variable(name="Yij",
				  calibration_value=cal.Yij0,
				  dimension='matrix',
				  idx_labels=[sectors,
				  sectors],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'I':Variable(name="I",
				  calibration_value=cal.I0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'aYij':Variable(name="aYij",
				  calibration_value=cal.aYij0 ,
				  dimension='matrix',
				  idx_labels=[sectors,
				  sectors],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  endo_names=endo_aYij_indexes),

    'pY_Ej':Variable(name="pY_Ej",
				  calibration_value=cal.pY_Ej,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pE_TT':Variable(name="pE_TT",
				  calibration_value=cal.pE_TT,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pE_TnT':Variable(name="pE_TnT",
				  calibration_value=cal.pE_TnT,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pE_B':Variable(name="pE_B",
				  calibration_value=cal.pE_B,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pE_Pj':Variable(name="pE_Pj",
				  calibration_value=cal.pE_Pj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),


    'pE_Ej':Variable(name="pE_Ej",
				  calibration_value=cal.pE_Ej,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  endo_names=["ENERGY"]),

    'wG':Variable(name="wG",
				  calibration_value=cal.wG,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, 1),
				  status="exo"),

    'GDPreal':Variable(name="GDPreal",
				  calibration_value=cal.GDPreal,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'tauSj':Variable(name="tauSj",
				  calibration_value=cal.tauSj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-1,
				  1),
				  status="exo"),

    'tauYj':Variable(name="tauYj",
				  calibration_value=cal.tauYj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-1,
				  1),
				  status="exo"),

    'bKLj':Variable(name="bKLj",
				  calibration_value=cal.bKLj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'pCtp':Variable(name="pCtp",
				  calibration_value=cal.pCjtp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=True,
				  bounds=(0, np.inf),
				  status="exo"),

    'Ctp':Variable(name="Ctp",
				  calibration_value=cal.Ctp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=True,
				  bounds=(0, np.inf),
				  status="exo"),

    'Gtp':Variable(name="Gtp",
				  calibration_value=cal.Gtp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=True,
				  bounds=(0, np.inf),
				  status="exo"),

    'Itp':Variable(name="Itp",
				  calibration_value=cal.Itp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=True,
				  bounds=(0, np.inf),
				  status="exo"),

    'pXtp':Variable(name="pXtp",
				  calibration_value=cal.pXtp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=True,
				  bounds=(0, np.inf),
				  status="exo"),

    'Xtp':Variable(name="Xtp",
				  calibration_value=cal.Xtp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=True,
				  bounds=(0, np.inf),
				  status="exo"),

    'Mtp':Variable(name="Mtp",
				  calibration_value=cal.Mtp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=True,
				  bounds=(0, np.inf),
				  status="exo"),
                  
    'alphaKj':Variable(name="alphaKj",
				  calibration_value=cal.alphaKj ,
				  dimension='vector',
				  idx_labels=sectors ,
				  is_t_minus_one=False ,
				  bounds=(0,1),
				  status = "exo"),

    'alphaLj':Variable(name="alphaLj",
				  calibration_value=cal.alphaLj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, 1),
				  status="exo"),

    'aKLj':Variable(name="aKLj",
				  calibration_value=cal.aKLj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  endo_names=["ENERGY"]),

    'alphaCj0':Variable(name="alphaCj0",
				  calibration_value=cal.alphaCj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'alphaGj':Variable(name="alphaGj",
				  calibration_value=cal.alphaGj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'alphaIj':Variable(name="alphaIj",
				  calibration_value=cal.alphaIj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'alphaXj':Variable(name="alphaXj",
				  calibration_value=cal.alphaXj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'alphaDj':Variable(name="alphaDj",
				  calibration_value=cal.alphaDj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'betaDj':Variable(name="betaDj",
				  calibration_value=cal.betaDj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'betaMj':Variable(name="betaMj",
				  calibration_value=cal.betaMj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'thetaj':Variable(name="thetaj",
				  calibration_value=cal.thetaj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'csij':Variable(name="csij",
				  calibration_value=cal.csij,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'sigmaXj':Variable(name="sigmaXj",
				  calibration_value=cal.sigmaXj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'sigmaSj':Variable(name="sigmaSj",
				  calibration_value=cal.sigmaSj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'sigmaKLj':Variable(name="sigmaKLj",
				  calibration_value=cal.sigmaKLj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'delta':Variable(name="delta",
				  calibration_value=cal.delta,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, 1),
				  status="exo"),

    'YE_Pj':Variable(name="YE_Pj",
				  calibration_value=cal.YE_Pj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'YE_Tj':Variable(name="YE_Tj",
				  calibration_value=cal.YE_Tj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'YE_Bj':Variable(name="YE_Bj",
				  calibration_value=cal.YE_Bj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'C_EB':Variable(name="C_EB",
				  calibration_value=cal.C_EB,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'C_ET':Variable(name="C_ET",
				  calibration_value=cal.C_ET,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'YE_Ej':Variable(name="YE_Ej",
				  calibration_value=cal.YE_Ej,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'aYE_Bj':Variable(name="aYE_Bj",
				  calibration_value=cal.aYE_Bj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'aYE_Pj':Variable(name="aYE_Pj",
				  calibration_value=cal.aYE_Pj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'aYE_Tj':Variable(name="aYE_Tj",
				  calibration_value=cal.aYE_Tj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'aKLj0':Variable(name="aKLj0",
				  calibration_value=cal.aKLj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'aYij0':Variable(name="aYij0",
				  calibration_value=cal.aYij0,
				  dimension='matrix',
				  idx_labels=[sectors,
				  sectors],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'pXj':Variable(name="pXj",
				  calibration_value=cal.pXj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names=["ENERGY","SERVICES"]),

    'rhoB':Variable(name="rhoB",
				  calibration_value=cal.rhoB,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'rhoTT':Variable(name="rhoTT",
				  calibration_value=cal.rhoTT,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf), 
                  status="exo"),

    'rhoTnT':Variable(name="rhoTnT",
				  calibration_value=cal.rhoTnT,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'rhoPj':Variable(name="rhoPj",
				  calibration_value=cal.rhoPj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'lambda_KLM':Variable("lambda_KLM",
				  cal.lambda_KLM,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    "R_E":Variable("R_E",
				  cal.R_E,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),
                  
    "R_nE":Variable("R_nE",
				  cal.R_nE,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'betaCj_nE':Variable(name="betaCj_nE",
				  calibration_value=cal.betaCj_nE,
				  dimension='vector',
				  idx_labels=sectors_nE,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'u_C':Variable(name="u_C",
				  calibration_value=cal.u_C,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),

    "gammaCj_nE":Variable(name="gammaCj_nE",
				  calibration_value=cal.gammaCj_nE,
				  dimension='vector',
				  idx_labels=sectors_nE,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    "A_Cj_nE":Variable(name="A_Cj_nE",
				  calibration_value=cal.A_Cj_nE,
				  dimension='vector',
				  idx_labels=sectors_nE,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    "normalisation_factor":Variable(name="normalisation_factor",
				  calibration_value=cal.normalisation_factor,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    }