import numpy as np 
from simple_calibration import calibrationVariables
from import_GTAP_data import sectors
from Variable_class import Variable

# This module defines the master dictionary of model variable specifications.
# Each entry maps a variable key to a configured ``Variable`` instance.
#
# Notes on ``is_t_minus_one``:
# - ``False`` means no lag linkage is used.
# - A string value means this variable aquires the value of the variable indicated by the string in the previous time step. 
# 	This is used to automatically populate the first year of the time-series DataFrame with the calibration value of the indicated variable, 
# 	and to set up the correct lag relationships for dynamic updating in the model solution process.


endo_aYij_indexes = [("ENERGY",x) for x in sectors]
sectors_nE     = [x for x in sectors if x != "ENERGY"]
sectors_plus_hh = sectors + ["HOUSEHOLDS"]
energy_types    = ["T", "B", "P", "PE"]
endo_aYij_indexes.extend([(x,"ENERGY") for x in sectors_nE])
cal = calibrationVariables()

VARIABLES_SPECS = {
    'K':Variable(name= "K",
                calibration_value=cal.K0, 
                dimension='scalar', 
                idx_labels=[], 
                is_t_minus_one=False, 
                bounds=(0, np.inf), 
                status="exo"),

    'wI':Variable(name= "wI", 
                  calibration_value=cal.wI, 
                  dimension='scalar', 
                  idx_labels=[], 
                  is_t_minus_one=False, 
                  bounds=(0, 1), 
                  status="exo"),

    'wB':Variable(name= "wB", 
                  calibration_value=cal.wB, 
                  dimension='scalar', 
                  idx_labels=[], 
                  is_t_minus_one=False, 
                  bounds=(-1, 1), 
                  status="exo"),

    'L':Variable(name= "L", 
                 calibration_value=cal.L0, 
                 dimension='scalar', 
                 idx_labels=[], 
                 is_t_minus_one=False, 
                 bounds=(0, np.inf), 
                 status="exo"),

    'pL': Variable(name= "pL",
                 calibration_value=cal.pL0,
                 dimension='scalar',
                 idx_labels=[],
                 is_t_minus_one=False,
                 bounds=(0,np.inf),
                 status="endo"),

    'pK':Variable(name= "pK",
				  calibration_value=cal.pK0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'pI':Variable(name= "pI",
				  calibration_value=cal.pI0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'B':Variable(name= "B",
				  calibration_value=cal.B0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),

    'R':Variable(name= "R",
				  calibration_value=cal.R0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'Ri':Variable(name= "Ri",
				  calibration_value=cal.Ri0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'Rg':Variable(name= "Rg",
				  calibration_value=cal.Rg0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'bKL':Variable(name= "bKL",
				  calibration_value=cal.bKL,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),

    'GDPPI':Variable(name= "GDPPI",
				  calibration_value=cal.GDPPI,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),

    'GDP':Variable(name= "GDP",
				  calibration_value=cal.GDPreal,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),
                  
    'Kj':Variable(name="Kj",
				  calibration_value=cal.Kj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  status="endo"),

    'Lj':Variable(name="Lj",
				  calibration_value=cal.Lj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'KLj':Variable(name="KLj",
				  calibration_value=cal.KLj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pKLj':Variable(name="pKLj",
				  calibration_value=cal.pKLj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Yj':Variable(name="Yj",
				  calibration_value=cal.Yj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pYj':Variable(name="pYj",
				  calibration_value=cal.pYj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Cj': Variable(name="Cj",
				  calibration_value=cal.Cj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pCj': Variable(name="pCj",
				  calibration_value=cal.pCj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Mj': Variable(name="Mj",
				  calibration_value=cal.Mj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names=["ENERGY"]),

    'pMj': Variable(name="pMj",
				  calibration_value=cal.pMj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names=["ENERGY"]),

    'Xj': Variable(name="Xj",
				  calibration_value=cal.Xj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names=["ENERGY"]),

    'Dj': Variable(name="Dj",
				  calibration_value=cal.Dj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pDj': Variable(name="pDj",
				  calibration_value=cal.pDj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Sj': Variable(name="Sj",
				  calibration_value=cal.Sj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'pSj': Variable(name="pSj",
				  calibration_value=cal.pSj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Gj': Variable(name="Gj",
				  calibration_value=cal.Gj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Ij': Variable(name="Ij",
				  calibration_value=cal.Ij0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'Yij': Variable(name="Yij",
				  calibration_value=cal.Yij0,
				  dimension='matrix',
				  idx_labels=[sectors,
				  sectors],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'I':Variable(name="I",
				  calibration_value=cal.I0,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'aYij':Variable(name="aYij",
				  calibration_value=cal.aYij0 ,
				  dimension='matrix',
				  idx_labels=[sectors,
				  sectors],
				  is_t_minus_one=False,
				  bounds=(0,np.inf),
				  endo_names=endo_aYij_indexes),

    'pY_Ej':Variable(name="pY_Ej",
				  calibration_value=cal.pY_Ej,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'E_vol':Variable(name="E_vol",
				  calibration_value=cal.E_vol,
				  dimension='matrix',
				  idx_labels=[sectors_plus_hh, energy_types],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names=[(s, "PE") for s in sectors_plus_hh]
				            + [("HOUSEHOLDS", "T"), ("HOUSEHOLDS", "B")]),

    'pE':Variable(name="pE",
				  calibration_value=cal.pE,
				  dimension='matrix',
				  idx_labels=[sectors_plus_hh, energy_types],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names=[(s, "PE") for s in sectors_plus_hh if s != "ENERGY"]),

    'rhoE':Variable(name="rhoE",
				  calibration_value=cal.rhoE,
				  dimension='matrix',
				  idx_labels=[sectors_plus_hh, energy_types],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'a_Ej':Variable(name="a_Ej",
				  calibration_value=cal.a_Ej,
				  dimension='matrix',
				  idx_labels=[sectors_plus_hh, energy_types],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'wG':Variable(name="wG",
				  calibration_value=cal.wG,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, 1),
				  status="exo"),

    'GDPreal':Variable(name="GDPreal",
				  calibration_value=cal.GDPreal,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'tauSj':Variable(name="tauSj",
				  calibration_value=cal.tauSj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-1,
				  1),
				  status="exo"),

    'tauYj':Variable(name="tauYj",
				  calibration_value=cal.tauYj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-1,
				  1),
				  status="exo"),

    'bKLj':Variable(name="bKLj",
				  calibration_value=cal.bKLj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'pCtp':Variable(name="pCtp",
				  calibration_value=cal.pCjtp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="pCj",
				  bounds=(0, np.inf),
				  status="exo"),

    'Ctp':Variable(name="Ctp",
				  calibration_value=cal.Ctp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="Cj",
				  bounds=(0, np.inf),
				  status="exo"),

    'Gtp':Variable(name="Gtp",
				  calibration_value=cal.Gtp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="Gj",
				  bounds=(0, np.inf),
				  status="exo"),

    'Itp':Variable(name="Itp",
				  calibration_value=cal.Itp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="Ij",
				  bounds=(0, np.inf),
				  status="exo"),

    'pXtp':Variable(name="pXtp",
				  calibration_value=cal.pXtp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="pXj",
				  bounds=(0, np.inf),
				  status="exo"),

    'Xtp':Variable(name="Xtp",
				  calibration_value=cal.Xtp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="Xj",
				  bounds=(0, np.inf),
				  status="exo"),

    'Mtp':Variable(name="Mtp",
				  calibration_value=cal.Mtp,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one="Mj",
				  bounds=(0, np.inf),
				  status="exo"),
                  
    'alphaKj':Variable(name="alphaKj",
				  calibration_value=cal.alphaKj ,
				  dimension='vector',
				  idx_labels=sectors ,
				  is_t_minus_one=False ,
				  bounds=(0,1),
				  status = "exo"),

    'alphaLj':Variable(name="alphaLj",
				  calibration_value=cal.alphaLj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, 1),
				  status="exo"),

    'aKLj':Variable(name="aKLj",
				  calibration_value=cal.aKLj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  endo_names=["ENERGY"]),

    'alphaCj0':Variable(name="alphaCj0",
				  calibration_value=cal.alphaCj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'alphaGj':Variable(name="alphaGj",
				  calibration_value=cal.alphaGj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'alphaIj':Variable(name="alphaIj",
				  calibration_value=cal.alphaIj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'alphaXj':Variable(name="alphaXj",
				  calibration_value=cal.alphaXj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'alphaDj':Variable(name="alphaDj",
				  calibration_value=cal.alphaDj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'betaDj':Variable(name="betaDj",
				  calibration_value=cal.betaDj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'betaMj':Variable(name="betaMj",
				  calibration_value=cal.betaMj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'thetaj':Variable(name="thetaj",
				  calibration_value=cal.thetaj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'csij':Variable(name="csij",
				  calibration_value=cal.csij,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'sigmaXj':Variable(name="sigmaXj",
				  calibration_value=cal.sigmaXj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'sigmaSj':Variable(name="sigmaSj",
				  calibration_value=cal.sigmaSj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'sigmaKLj':Variable(name="sigmaKLj",
				  calibration_value=cal.sigmaKLj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'delta':Variable(name="delta",
				  calibration_value=cal.delta,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, 1),
				  status="exo"),

    'aKLj0':Variable(name="aKLj0",
				  calibration_value=cal.aKLj0,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'aYij0':Variable(name="aYij0",
				  calibration_value=cal.aYij0,
				  dimension='matrix',
				  idx_labels=[sectors,
				  sectors],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    'pXj':Variable(name="pXj",
				  calibration_value=cal.pXj,
				  dimension='vector',
				  idx_labels=sectors,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  exo_names=["ENERGY","SERVICES"]),

    'lambda_KLM':Variable("lambda_KLM",
				  cal.lambda_KLM,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    "R_E":Variable("R_E",
				  cal.R_E,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),
                  
    "R_nE":Variable("R_nE",
				  cal.R_nE,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="endo"),

    'betaCj_nE':Variable(name="betaCj_nE",
				  calibration_value=cal.betaCj_nE,
				  dimension='vector',
				  idx_labels=sectors_nE,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    'u_C':Variable(name="u_C",
				  calibration_value=cal.u_C,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="endo"),

    "gammaCj_nE":Variable(name="gammaCj_nE",
				  calibration_value=cal.gammaCj_nE,
				  dimension='vector',
				  idx_labels=sectors_nE,
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    "A_Cj_nE":Variable(name="A_Cj_nE",
				  calibration_value=cal.A_Cj_nE,
				  dimension='vector',
				  idx_labels=sectors_nE,
				  is_t_minus_one=False,
				  bounds=(0, np.inf),
				  status="exo"),

    "normalisation_factor":Variable(name="normalisation_factor",
				  calibration_value=cal.normalisation_factor,
				  dimension='scalar',
				  idx_labels=[],
				  is_t_minus_one=False,
				  bounds=(-np.inf,np.inf),
				  status="exo"),

    }